# Generated by Django 2.2.7 on 2020-01-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business',
            new_name='activity',
        ),
    ]
