# Generated by Django 2.2.7 on 2020-01-12 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200111_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='api.Activity'),
        ),
    ]
